#!/usr/bin/env bash
# Configure Nginx server to redirecting to error page

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "/server_name _;/ a rewrite ^/redirect_me https://youtube.com;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo sed -i "/server_name _;/ a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
