#!/usr/bin/env bash
# Print Holberton School and good luck and bad luck at 
# spot 8th and 4th
i=1
while [ $i -le 10 ]; do
    if [[ $i -eq 4 ]]; then
        echo "bad luck"
    elif [[ $i -eq 8 ]]; then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    i=$(( i + 1 ))
done
