#!/usr/bin/env bash
# set nginx user

sudo service nginx stop
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx nginx
sudo service nginx start
